# Generated by Django 6.0.3 on 2026-03-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical')], default='theory', max_length=20),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='semester_type',
            field=models.CharField(choices=[('odd', 'Odd Semester'), ('even', 'Even Semester')], default='odd', max_length=10),
        ),
        migrations.AddField(
            model_name='timeslot',
            name='is_lunch',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='room_type',
            field=models.CharField(choices=[('lecture', 'Lecture Hall'), ('lab', 'Laboratory'), ('computer_lab', 'Computer Lab')], default='lecture', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
